apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sr3id5qs3-python
  janus-idp.io/tekton: sr3id5qs3-python
  backstage.io/kubernetes-id: sr3id5qs3-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sr3id5qs3-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
